[pytest]
# for forcing pytest to not get from wandering off into /opt/ros/jazzy/ etc. 
pythonpath = . 
addopts = --import-mode=importlib
markers =
    integration: marks tests as integration tests that require the Ollama server (deselect with '-m "not integration"')